HotelSystem/Controllers/BookingController.cs
using HotelSystem.Logic;
using HotelSystem.Models;
using HotelSystem.ViewModels;
using System.Web.Mvc;

namespace HotelSystem.Controllers
{
    public class BookingController : Controller
    {
        private readonly HotelDBEntities dbContext;
        private readonly BookingLogic _bookingLogic;

        // GET: Room

        public BookingController()
        {
            dbContext = new HotelDBEntities();
            _bookingLogic = new BookingLogic();
        }


        public ActionResult Index()
        {
            return View(_bookingLogic.GetBookingVmWithFreeRooms());
        }

        [HttpPost]
        public ActionResult AddBooking(BookingViewModel bookingViewModel)
        {
            if (_bookingLogic.AddBooking(bookingViewModel) != null)
                return Json(new { message = "Booking is done successfully", success = true }, JsonRequestBehavior.AllowGet);
            return Json(new { message = "Failed to add Booking", success = false }, JsonRequestBehavior.AllowGet);

        }

        [HttpGet]
        public PartialViewResult GetAllBookingHistory()
        {
            return PartialView("_BookingHistoryPartial", _bookingLogic.GetAllBookings());
        }



    }
}

HotelSystem/Controllers/RoomController.cs
using HotelSystem.Logic;
using HotelSystem.Models;
using HotelSystem.ViewModels;
using System.Web.Mvc;

namespace HotelSystem.Controllers
{
    public class RoomController : Controller
    {
        private readonly HotelDBEntities dbContext;
        private RoomLogic _roomLogic;

        // GET: Room

        public RoomController()
        {
            dbContext = new HotelDBEntities();
            _roomLogic = new RoomLogic();
        }

        public ActionResult Index()
        {
            return View(_roomLogic.GetRoomTypesAndBookingTypes());
        }

        [HttpPost]
        public ActionResult Index(RoomViewModel roomViewModel)
        {

            if (roomViewModel.RoomId == 0)
            {
                if (_roomLogic.AddRoom(roomViewModel) != null)
                    return Json(new { success = true, type = "add", message = "Room Added successfull" }, JsonRequestBehavior.AllowGet);
                else
                    return Json(new { success = false, message = "Failed to Add Room" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                if (_roomLogic.EditRoom(roomViewModel))
                    return Json(new { success = true, type = "update", message = "Room Updated successfull" }, JsonRequestBehavior.AllowGet);
                else
                    return Json(new { success = false, message = "Failed to update room" }, JsonRequestBehavior.AllowGet);
            }


        }

        public JsonResult DeleteRoom(int roomId)
        {
            if (_roomLogic.DeleteRoom(roomId))
                return Json(new { success = true, message = "Record Deleted Successfully" }, JsonRequestBehavior.AllowGet);

            return Json(new { success = false, message = "Failed to delete record" }, JsonRequestBehavior.AllowGet);

        }




        public PartialViewResult GetAllRooms()
        {
            return PartialView("_RoomDetailPartial", _roomLogic.GetAllRooms());
        }

        [HttpGet]
        public JsonResult EditRoom(int roomId)
        {
            return Json(_roomLogic.GetRoom(roomId), JsonRequestBehavior.AllowGet);
        }



    }
}

HotelSystem/Views/Shared/_BookingHistoryPartial.cshtml
@model IEnumerable<HotelSystem.ViewModels.RoomBokingViewModel>
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<table class="table-responsive table-hover table-bordered" style="width:100%">
    <thead>
        <tr style="background-color: cornflowerblue; height: 40px;font-size:17px;">
            <th class="text-center">Name</th>
            <th class="text-center">Address</th>
            <th class="text-center">Phone</th>
            <th class="text-center">Booking From</th>
            <th class="text-center">Booking To</th>
            <th class="text-center">Room</th>
            <th class="text-center">Members</th>
            <th class="text-center">Days</th>
            <th class="text-center">price</th>
            <th class="text-center">total Amount</th>
        </tr>

    </thead>

    <tbody>
        @foreach (var item in Model)
        {
        <tr class="text-center" style="padding-top: 40px; font-size: 15px; height: 50px;">

            <td class="text-center">@item.CustomerName</td>
            <td class="text-center">@item.CustomerAddress</td>
            <td class="text-center">@item.CustomerPhone</td>
            <td class="text-center">@item.BookingFrom.ToString("dd-MM-yyyy")</td>
            <td class="text-center">@item.BookingTo.ToString("dd-MM-yyyy")</td>
            <td class="text-center">@item.RoomNumber</td>
            <td class="text-center">@item.NumberOfMembers</td>
            <td class="text-center">@item.NumberOfDays</td>
            <td class="text-center">@item.RoomPrice.ToString("#,##0.00")</td>
            <td class="text-center">@item.totalAmount.ToString("#,##0.00")</td>
        </tr>


        }
    </tbody>
</table>

HotelSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hotely</title>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Hotely", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Rooms", "Index", "Room")</li>
                    <li>@Html.ActionLink("Bookings", "Index", "Booking")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

HotelSystem/Views/Shared/_RoomDetailPartial.cshtml
@model IEnumerable<HotelSystem.ViewModels.RoomDetailViewModel>


<table class="table-responsive table-hover table-bordered" style="width:100%">
    <thead >
        <tr style="background-color: cornflowerblue;height: 40px;font-size:17px;">
            <th class="text-center">Action</th>
            <th class="text-center">Image</th>
            <th class="text-center">Room No</th>
            <th class="text-center">Price</th>
            <th class="text-center">Status</th>
            <th class="text-center">Type</th>
            <th class="text-center">Capacity</th>
        </tr>

    </thead>

    <tbody >
        @foreach (var item in Model)
        {
            <tr class="text-center" style="padding-top:40px;font-size:15px;height:10px;">
                <td class="text-center">
                    <span id="btnDelete" class="glyphicon glyphicon-trash" onclick="DeleteRoom(@item.RoomId)"></span>&nbsp;
                    <span id="btnEdit" class="glyphicon glyphicon-pencil" onclick="EditRoom(@item.RoomId)"></span>&nbsp;
                </td>
                <td class="text-center">

                <img src="@Url.Content("~/Images/" + item.RoomImage)" 
                     width="80"height="80" style="margin-left:auto;margin-right:auto" class="img-responsive text-center" />
                </td>
                <td class="text-center">@item.RoomNumber</td>
                <td class="text-center">@item.RoomPrice</td>
                <td class="text-center">@item.BookingStatus</td>
                <td class="text-center">@item.RoomType</td>
                <td class="text-center">@item.RoomCapacity</td>
            </tr>


        }
    </tbody>
</table>